url: "kanennn.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

license: "MIT"
license_url: "LICENSE"

repo_url: "github.com/kanennn/kanennn.github.io"
repo_host: "GitHub"

author: "kanennn"
name: "kanen stephens"

header_links: [["about/", "about"], ["log/", "log"], ["projects/", "projects"]]

github: "https://github.com/kanennn"
youtube: "https://www.youtube.com/@kkanennn"
twitch: "https://www.twitch.tv/kkakennn"
instagram: "https://www.instagram.com/kakanennn/"
bluesky: "https://bsky.app/profile/kanennn.bsky.social"
